version: '3'

services:
  WordPress:
    image: wordpress:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: tno-user
      WORDPRESS_DB_PASSWORD: tno-secret
      WORDPRESS_DB_NAME: TNO
    volumes:
      - wordpress:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: TNO
      MYSQL_USER: tno-user
      MYSQL_PASSWORD: tno-secret
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
