name: "Deployment Workflow"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  COMPOSER_CONFIGS: plugins/*/composer.json

jobs:
  build_push:
    name: "Build and push docker image"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_branch
        shell: bash

      - name: Build docker image and publish to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ format('{0}/{1}', github.repository, steps.extract_branch.outputs.branch)  }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: deployment.Dockerfile

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    deploy:
        #needs: build_push
        name: "Deploy the published image"
        runs-on: ubuntu-latest

        steps:                 
            -   name: SSH-ing into EC2 instance
                uses: garygrossgarten/github-action-ssh@release
                with:
                    command: sudo bash /home/ubuntu/deploy.sh
                    host: ${{ secrets.HOST }}
                    username: ubuntu
                    passphrase: ${{ secrets.PASSPHRASE }}
                    privateKey: ${{ secrets.PRIVATE_KEY}}
=======
  deploy:
=======
  deploy:
    needs: build_push

>>>>>>> 8827670... Fixed tabs
    name: "Deploy the published image"
=======
#  deploy:
#    needs: build_push

#    name: "Deploy the published image"
>>>>>>> b4adcbb... Update deployment.yml
=======
  deploy:
    needs: build_push

    name: "Deploy the published image"
>>>>>>> 48901b8... Update deployment.yml

    runs-on: ubuntu-latest

    env:
      CI: true

<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 48901b8... Update deployment.yml
    steps:
      - name: SSH-ing into EC2 instance
        uses: garygrossgarten/github-action-ssh@release
        with:
<<<<<<< HEAD
<<<<<<< HEAD
          command: ls -a
=======
          command: sudo bash /home/ubuntu/deploy.sh
>>>>>>> 8827670... Fixed tabs
=======
          command: sudo bash /home/ubuntu/deploy.sh
>>>>>>> 48901b8... Update deployment.yml
          host: ${{ secrets.HOST }}
          username: ubuntu
          passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 2a5c778... Reformatted workflow files
=======
>>>>>>> 8827670... Fixed tabs
=======
#    steps:
#      - name: SSH-ing into EC2 instance
#        uses: garygrossgarten/github-action-ssh@release
#        with:
#          command: sudo bash /home/ubuntu/deploy.sh
#          host: ${{ secrets.HOST }}
#          username: ubuntu
#          passphrase: ${{ secrets.PASSPHRASE }}
#          privateKey: ${{ secrets.PRIVATE_KEY}}
>>>>>>> b4adcbb... Update deployment.yml
=======
>>>>>>> 48901b8... Update deployment.yml
