name: "Deployment Workflow"

on: [push]

env:
    COMPOSER_FILES: plugins/*/composer.json

jobs:
    build_push:
        name: "Build and push docker image"

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Install dependencies for deployment
                run: |
                    for i in $(ls -1 "$COMPOSER_FILES");
                        do composer install \
                            --no-ansi \
                            --no-dev \
                            --no-interaction \
                            --no-plugins \
                            --no-progress \
                            --no-scripts \
                            --no-suggest \
                            --optimize-autoloader \
                            -d $(dirname "$i");
                    done;

            -   name: Publish to Registry
                uses: elgohr/Publish-Docker-Github-Action@master
                with:
                    name: lsvh/hbo-ict-inno-s2-tno/wp-essif-lab
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
                    registry: docker.pkg.github.com