name: "Deployment Workflow"

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

env:
    DOCKER_IMAGE_NAME: wp-essif-lab
    COMPOSER_CONFIGS: plugins/*/composer.json
    COMPOSER_VENDORS: plugins/*/vendor

jobs:
    build_push:
        name: "Build and push docker image"

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Check composer configs existence
                id: has_composer_configs
                uses: andstor/file-existence-action@v1
                with:
                    files: "plugins/*/composer.json"

            -   name: Install dependencies for deployment
                if: steps.has_composer_configs.outputs.files_exists == 'true'
                run: |
                    for i in $(ls -1 "$COMPOSER_CONFIGS");
                        do composer install \
                            --no-ansi \
                            --no-dev \
                            --no-interaction \
                            --no-plugins \
                            --no-progress \
                            --no-scripts \
                            --no-suggest \
                            --optimize-autoloader \
                            -d $(dirname "$i");
                    done;

            -   name: Check composer vendors existence
                id: has_composer_vendors
                uses: andstor/file-existence-action@v1
                with:
                    files: "$COMPOSER_VENDORS"

            -   name: Publish to Registry
                uses: elgohr/Publish-Docker-Github-Action@master
                if: steps.has_composer_vendors.outputs.files_exists == 'true'
                with:
                    name: ${{ github.repository }}/$DOCKER_IMAGE_NAME
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
                    registry: docker.pkg.github.com