version: '3'


volumes:
    db_data:
    wp_data:
    wp_plugins:

networks:
    backend:

services:
    app:
        depends_on:
            - db
            - wp
        image: ${APP_IMG}
        env_file: 
            - .env
        environment:
            WP_HOST: ${WP_HOST} # default: http://localhost
            WP_USER: ${WP_USER} # default: admin
            WP_PASS: ${WP_PASS}
        volumes:
            - wp_data:/var/www/html
            - wp_plugins:/var/www/html/wp-content/plugins
        networks:
            - backend

    wp:
        depends_on:
            - db
        image: wordpress
        restart: always
        ports:
            - 80:80
        env_file: 
            - .env
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: ${DB_USER}
            WORDPRESS_DB_PASSWORD: ${DB_PASS}
            WORDPRESS_DB_NAME: ${DB_NAME}
        volumes:
            - wp_data:/var/www/html
            - wp_plugins:/var/www/html/wp-content/plugins
        networks:
            - backend

    db:
        image: mysql:5.7
        restart: always
        env_file: 
            - .env
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        networks:
            - backend
